### ISSUE TITLE
PacketPlayInUserEntety bug

### ISSUE THREAD

**Issue by krusic22** [HorizonCode/PNCP#14]
This happens when running PaperSpigot 1.12 with ProtocolSupport (also happens on normal Spigot). I assume this happens because it disables delay but PNCP does not detect that.
https://pastebin.com/GLfxFqK5 (since GitHub kills the formatting)

**Comment by HorizonCode** [comment]
download the latest version.
1.12 Support was added.

**Comment by krusic22** [comment]
Thanks!
