### ISSUE TITLE
torchspigot error

### ISSUE THREAD

**Issue by mat41997** [HorizonCode/PNCP#2]
logs
https://gist.github.com/mat41997/6c341c155140776d6f918e2a4e47ca09

thema
https://github.com/TorchSpigot/Torch/issues/80

**Comment by HorizonCode** [comment]
Currently only Supporting Spigot/CraftBukkit. 
Im looking forward to add PaperSpigot and TorchSpigot support :)

**Comment by mat41997** [comment]
ok. now works on torchspigot
