### ISSUE TITLE
Scaffold Problem

### ISSUE THREAD

**Issue by sKye27** [HorizonCode/PNCP#3]
When player uses scaffold to go up anticheat dont detects him

**Comment by HorizonCode** [comment]
video material? to see how the player is scaffoldwalking?

**Comment by sKye27** [comment]
i was testing the plugin and when you place block to go up scffolddont detects him

**Comment by HorizonCode** [comment]
check that you dont have op or admin pemissions, and make an video of that bypass, an upload it on youtube.
