### ISSUE TITLE
Elytra false-positive

### ISSUE THREAD

**Issue by Amenixx** [HorizonCode/PNCP#4]
When someone try to use the fireworks while flying, it throw an alert of "speed". Same when someone is landing.

**Comment by CaptainObvious0** [comment]
The cheat is pretty well covered with NoCheatPlus, so it could be removed. NoCheatPlus has the same issue but was able to solve it in build 1059 & 1058.

Link to issue: https://github.com/NoCheatPlus/Issues/issues/347

**Comment by HorizonCode** [comment]
removed Elytra check.
